### ISSUE TITLE
how can  calculate specificity using simulated repertoire?

### ISSUE THREAD

**Issue by yirenheihei** [jao321/YClon#2]
hi,I read your paper about Yclon.It is very great,but I have a question: In simulated repertoire,how can  calculate TN 、FP、TP、FN ?thank you

**Comment by jao321** [comment]
Oh hey!

We calculate TN, FP, TP and FN very similar to how you calculate it for  a diagnosis test.

As we are working with simulated repertoires, we know exactly which sequences are grouped together as clonotype. If YClon group those sequences in the same clonotype we treat that as a True Positive (TP). And you might question how did we decide which YClon clonotype best represent those sequences. We observe the mode(most common) clone_id among those sequences and define it as the "correct" clone_id. 

Now we see how many sequences are clonotyped as being part of that clone_id, that are not in the assign in the simulated repertoire as part of the same clonotype, those we call False Positive(FP).

If a sequence is part of a clonotype determined in the simulated repertoire, but not in the YClon output, those are False Negative (FN).

And lastly, if a sequence is not part of the clonotype in the simulated repertoire and it is also not in YClon, that would be the True Positive (TP).

I hope I could solve your questions. If you have any other, let me know.

**Comment by yirenheihei** [comment]
Thank you very much for your prompt reply, but I'm still a bit confused about the calculations. Could you please provide me with the code for these calculations?
my code is below:
`       

        truth_value=set(truth_dict[item[0]])###simulated clonotype
        predict_value=set(predict_dict[item[1]])###predict clonotype
        
        tp=len(list(truth_value & predict_value))
        tn=len(list(truth_value - predict_value))
        fp=len(list(predict_value-truth_value))
        fn=len(list((all_seqs-truth_value) & (all_seqs -predict_value)))###all_seqs is the all sequences of a sample

        specificity=tn/(tn+fp)*1.0
        sensitivity=tp/(tp+fn)*1.0  `
thank you

**Comment by jao321** [comment]
Sorry for the delayed response.

If I am not wrong, this is the code I used to calculate it, it is pretty similar to yours.

     real <- unique(yc$clone_truth)
      ct = 0
     
    for (i in (1:length(real))){
      setAC <- subset(yc$clone_id,yc$clone_truth == i)
      setBD <- subset(yc$clone_id,yc$clone_truth != i)
  
      predict <- modes(setAC)
  
      if(length(predict) != 1){
        predict <- predict[1]
      }
  
      tp <- length(subset(setAC, setAC==predict))
      fn <- length(setAC) - tp
      fp <- length(subset(setBD, setBD==predict))
      tn <- length(setBD) - fp
      specificity <- tn/(tn+fp)
      sensitivity <- (tp/(tp+fn))
      ppv <- (tp/(tp+fp))
    }

The mode function just gets the most common value, the mode.

**Comment by yirenheihei** [comment]
thank you very much.
